{
 "title": "Compras",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Desempenhos de Vendas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sobre",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Estes dashboards monitoram métricas como volume de vendas, receita, lucro, taxa de conversão e tamanho médio do pedido. Eles podem ajudar a identificar tendências, monitorar o progresso em relação às metas e informar estratégias de vendas e marketing."
   }
  },
  {
   "title": "Histograma de compras",
   "type": "histogram",
   "description": "Este painel apresenta um histograma dos tempos de compra dos clientes. Cada linha no gráfico representa um percentil específico dos tempos de compra. \n\n- A linha do percentil 50 (mediana) mostra o tempo de compra em que metade dos clientes conclui suas compras.\n- A linha do percentil 75 mostra o tempo de compra em que 75% dos clientes conclui suas compras.\n- A linha do percentil 90 mostra o tempo de compra em que 90% dos clientes conclui suas compras.\n- A linha do percentil 95 mostra o tempo de compra em que 95% dos clientes conclui suas compras.\n- A linha do percentil 99 mostra o tempo de compra em que 99% dos clientes conclui suas compras.\n\nAs linhas adicionais (60, 70, 80, 85 percentis) fornecem uma visão mais detalhada da distribuição dos tempos de compra.\n\nEste histograma pode ajudar a identificar tendências e outliers nos tempos de compra, informando decisões sobre onde focar os esforços de otimização.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.60, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.85, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_compra_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contador de compras",
   "type": "timeseries",
   "description": "Número total de compras feitas",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "total_compras" }
   ]
  },
  {
   "title": "Taxa de Compras em Tempo Real",
   "type": "timeseries",
   "description": "Taxa de compras em tempo real, calculada como o número de compras por segundo",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "por segundo" } },
   "targets": [
    {
     "expr": "irate(total_compras[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Comportamento do Cliente",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sobre",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": " Estes dashboards rastreiam métricas como taxa de retenção, tempo médio no site, taxa de abandono do carrinho e atividade do usuário. Eles podem ajudar a entender o comportamento do cliente, identificar problemas e oportunidades e melhorar a experiência do cliente."
     }
    }
   ]
  },
  {
   "title": "Métricas Operacionais",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sobre",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "options": {
      "content": "Estes dashboards rastreiam métricas como tempo de processamento de pedidos, eficiência do estoque e tempo de entrega. Eles podem ajudar a identificar gargalos, melhorar a eficiência operacional e reduzir custos."
     }
    }
   ]
  },
  {
   "title": " Métricas Financeiras",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sobre",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "options": {
      "content": " Estes dashboards monitoram métricas como receita, lucro, custos operacionais e retorno sobre o investimento. Eles podem ajudar a monitorar a saúde financeira da empresa, informar decisões de orçamento e investimento e garantir a rentabilidade."
     }
    }
   ]
  },
  {
   "title": "Desempenho dos Serviços",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sobre",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
     "options": {
      "content": "Estes dashboards monitoram métricas como tempo de resposta, taxa de erro, tempo de atividade e uso de recursos. Eles podem ajudar a identificar problemas técnicos, garantir a confiabilidade e a disponibilidade das aplicações e melhorar a eficiência."
     }
    }
   ]
  }
 ]
}