fullnameOverride: prometheus

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  adminPassword: Vertigo123
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:

      # ShopMetrics360
      - name: shopmetrics360
        orgId: 1
        folder: 'ShopMetrics360'
        type: file
        options:
          path: /var/lib/grafana/dashboards/shopmetrics360

  dashboardsConfigMaps:

    # ShopMetrics360
    shopmetrics360: shopmetrics360-dashboard

prometheusOperator:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "shopmetrics360"
        static_configs:
          - targets: ["shopmetrics360.default.svc.cluster.local"]  

