fullnameOverride: prometheus

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  adminPassword: Vertigo123

prometheusOperator:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "histograma"
        static_configs:
          - targets: ["histograma.default.svc.cluster.local"]  

